production:
  transient_environment: true
  production_environment: false
  payload:
    user: test
  environment: production
staging:
 transient_environment: true
 production_environment: false
 payload:
   user: test
 environment: staging
