name: deliver deploy

on:
  workflow_dispatch:
    inputs:
      beanstalk-env:
        description: Beanstalk Env
        required: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Test input
        with:
          BEANSTALK_WITH: ${{ github.event.inputs.logLevel }}
        env:
          BEANSTALK: ${{ github.event.inputs.logLevel }} 
        run: |
          echo "testing input: ${{ github.event.inputs.logLevel }}"
          echo "print env $INPUT_BEANSTALK-ENV"
          echo "print preset env $BEANSTALK"
          echo $GITHUB_REF
