name: deliver deploy

on:
  workflow_dispatch:
    inputs:
      beanstalk_env:
        description: Beanstalk Environment
        required: false
        default: 'firstleaf-production'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Test input
        env:
          BEANSTALK: ${{ github.event.inputs.logLevel }} 
        run: |
          echo "testing input: ${{ github.event.inputs.beanstalk_env }}"
          echo "print env $INPUT_BEANSTALK_ENV"
          echo "print preset env $BEANSTALK"
          echo $GITHUB_REF
