name: deploy

on:
  deployment:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: 'deployment pending'
      uses: 'deliverybot/deployment-status@master'
      with:
        state: 'pending'
        token: '${{ github.token }}'

    - uses: actions/checkout@v1
      with:
          fetch-depth: 1

    - name: Deploy to production
      if: (github.event.deployment.environment == 'production' && github.ref == 'refs/heads/master')
      uses: hmarr/debug-action@master

    - name: Deploy to dev bucket
      if: endsWith(github.event.deployment.environment, 'dev.firstleaf.club')
      env:
        TARGET_ADDRESS: https://${{github.event.deployment.payload.user}}.dev.firstleaf.club
        AWS_BUCKET: firstleaf-www-${{github.event.deployment.payload.user}}
        #GITHUB_CONTEXT: ${{ toJson(github) }}
        #EVENT_VAR: ${{ toJson(github.event) }}
        #ENVIROMENT_VAR: ${{ toJson(github.event.deployment.environment) }}
        #USER: ${{ toJson(github.event.deployment.environment) }}
      uses: hmarr/debug-action@master

    - name: 'deployment success'
      if: success()
      uses: 'deliverybot/deployment-status@master'
      with:
        state: 'success'
        token: '${{ github.token }}'
        description: 'App deployed to www.example.com'

    - name: 'deployment failure'
      if: failure()
      uses: 'deliverybot/deployment-status@master'
      with:
        state: 'failure'
        token: '${{ github.token }}'

        #    - name: update deploy status
        #if: always()
        #uses: unacast/actions-github-deployment-status@master
        #with:
        #github_token: ${{ secrets.GITHUB_TOKEN }}
        #status: ${{ job.status }}
