name: Deploy

on:
  deployment

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'deployment pending'
        uses: 'deliverybot/deployment-status@master'
        with:
          state: 'pending'
          token: '${{ github.token }}'
      - uses: actions/checkout@v2
      - name: "Setup ruby"
        uses: ruby/setup-ruby@v1
      - name: Echo ref num
        env:
          RefKey: master
          VERSION: ${{ github.sha }}
        run: |
          echo `git show-ref -s master`
          echo $GITHUB_SHA
          echo $GITHUB_REF
          echo $VERSION
          echo ${{ github.event.client_payload.message.beanstalk-env || secrets.BEANSTALK_ENV }}

      - name: Env variables
        uses: hmarr/debug-action@master
      #- name: Setup tmate session
      #uses: mxschmitt/action-tmate@v2
      - uses: actions/cache@v2
        env:
          RefKey: master
        with:
          path: vendor/bundle
          #key: ${{ runner.os }}-gems-${{ hashFiles('.ruby-version') }}-${{ hashFiles('**/Gemfile.lock') }}
          key: master-cache
          #restore-keys: |
          #  ${{ runner.os }}-gems-${{ hashFiles('.ruby-version') }}-
      - name: 'deployment success'
        if: success()
        uses: 'deliverybot/deployment-status@master'
        with:
          state: 'success'
          token: '${{ github.token }}'
          description: 'App deployed'
