name: deploy

on:
  deployment:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: 'deployment pending'
      uses: 'deliverybot/deployment-status@master'
      with:
        state: 'pending'
        token: '${{ github.token }}'

    - uses: actions/checkout@v1
      with:
          fetch-depth: 1

    - name: Print env variables (debug)
      env:
        TARGET_ADDRESS: https://${{github.actor}}.dev.firstleaf.club
        GITHUB_CONTEXT: ${{ toJson(github) }}
        EVENT_VAR: ${{ toJson(github.event) }}
        ENVIROMENT_VAR: ${{ toJson(github.event.deployment.environment) }}
        AWS_BUCKET: firstleaf-www-${{github.actor}}
      uses: hmarr/debug-action@master

    - name: 'deployment success'
      if: success()
      uses: 'deliverybot/deployment-status@master'
      with:
        state: 'success'
        token: '${{ github.token }}'
        description: 'App deployed to www.example.com'

    - name: 'deployment failure'
      if: failure()
      uses: 'deliverybot/deployment-status@master'
      with:
        state: 'failure'
        token: '${{ github.token }}'

        #    - name: update deploy status
        #if: always()
        #uses: unacast/actions-github-deployment-status@master
        #with:
        #github_token: ${{ secrets.GITHUB_TOKEN }}
        #status: ${{ job.status }}
