name: deploy

on:
  pull_request:
    types: [labeled]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
          fetch-depth: 1
    - name: Setup tmate session (debug)
      uses: mxschmitt/action-tmate@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
