name: Deploy

on:
  deployment:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Setup ruby"
        uses: ruby/setup-ruby@v1
      - name: Echo ref num
        env:
          RefKey: master
        run: |
          echo `git show-ref -s master`
          echo $GITHUB_SHA
          echo $GITHUB_REF
          echo $RefKey
      #- name: Env variables
      #  uses: hmarr/debug-action@master
      - uses: actions/cache@v2
        env:
          RefKey: master
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('.ruby-version') }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-${{ hashFiles('.ruby-version') }}-
      # Debug console
      #- name: Setup tmate session (debug)
      #  uses: mxschmitt/action-tmate@v1
