name: RSpec

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    if: github.event.pull_request.draft == 'false'
    runs-on: ubuntu-latest
    timeout-minutes: 15

    services:
      db:
        image: postgres:11-alpine
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: penrose
          POSTGRES_USER: penrose
          POSTGRES_DB: penrose_test
        options: >-
          --health-cmd pg_isready
          --health-interval 2s
          --health-timeout 1s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: "Setup ruby"
      uses: ruby/setup-ruby@v1
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ secrets.CHANGE_THIS_TO_INVALIDATE_CACHE }}-${{ hashFiles('.ruby-version') }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-${{ secrets.CHANGE_THIS_TO_INVALIDATE_CACHE }}-${{ hashFiles('.ruby-version') }}-
    - name: Build and test with rake
      env:
        RAILS_ENV: test
        DD_TRACE_STARTUP_LOGS: false
      run: |
        sudo apt-get -yqq install libpq-dev
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        bundle exec rails db:create
        bundle exec rails db:schema:load
        bundle exec rails db:migrate
        bundle exec rails db:test:prepare
        bundle exec rake 
