name: deploy

on:
  repository_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
          fetch-depth: 1

    - name: Env variables
      uses: hmarr/debug-action@master

    - name: Echo ref num
      run: |
        echo `git show-ref -s master`
        echo $GITHUB_SHA

    #- name: Debug session
    #  uses: mxschmitt/action-tmate@v1 
